#!/bin/sh

while IFS= read -r line; do
    case "$line" in
        *'account/rateLimits/read'*)
            printf '%s\n' '{"id":1,"result":{"rateLimits":{"primary":{"usedPercent":7,"windowDurationMins":10080,"resetsAt":1788271990},"secondary":{"usedPercent":42,"windowDurationMins":300,"resetsAt":1787699106}}}}'
            ;;
    esac
done
